include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - base

base:
  variables:
    EXTRA_TOOLS_COMMIT: $CI_COMMIT_SHA
    EXTRA_TOOLS_BRANCH: $CI_COMMIT_BRANCH
  stage: cloud
  trigger:
    project: se-ops/docker/matomo-docker-base
    branch: develop
