include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - base

base:
  variables:
    EXTRA_TOOLS_COMMIT: $CI_COMMIT_SHA
    EXTRA_TOOLS_BRANCH: $CI_COMMIT_BRANCH
  stage: base
  trigger:
    project: $BASE_REPO
    branch: $BASE_BRANCH
