version: '3'
services:
  selenium:
    container_name: selenium
#    image: seleniarm/standalone-chromium:113.0
    image: selenium/standalone-chrome:113.0
    ports:
     - 4444:4444
    shm_size: 2g
  matomo:
    container_name: matomo
    image: "${IMAGE:-digitalist/matomo:5.x-pcov}"
    volumes:
      - matomo-volume:/var/www/html:rw
      - $PWD:/var/www/html/plugins/ExtraTools
      - ./tests/ci/config/install.json:/var/www/html/config/install.json
    environment:
      - MATOMO_DB_USERNAME=root
      - MATOMO_DB_PASSWORD=root
      - MATOMO_DB_HOST=db
      - MATOMO_DB_NAME=matomo
      - MATOMO_DB_PREFIX=matomo_
      - MATOMO_URL=http://web
    depends_on:
      - db
  web:
    container_name: web
    image: nginx:alpine
    volumes:
      - ./tests/ci/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - matomo-volume:/var/www/html
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - matomo
    ports:
      - 80:80
    links:
       - matomo
  db:
    image: mariadb:10.1
    container_name: db
    command: --init-file /data/application/init.sql --max_allowed_packet=67108864
    volumes:
      - ./tests/ci/config/mysql/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  matomo-volume:
